# https://github.com/marketplace/actions/enforce-pr-labels
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "minor,major"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['minor','major']"
        BANNED_LABELS: ["do not merge", "wip"]
